project_id = "nkmxevmioczcmnldreyo"

[functions.nov-hub-api]
verify_jwt = false

[functions.dbf-business-data-api]
verify_jwt = false

[functions.nov-talent-readonly-api-v2]
verify_jwt = false

[functions.nov-talent-staging-readonly-api]
verify_jwt = false

[functions.nov-talent-write-api]
verify_jwt = false

[functions.send-line-works-notifications]
verify_jwt = true
