import assert from 'node:assert/strict'; import {createHash} from 'node:crypto'; import {mkdtemp,readFile,rm} from 'node:fs/promises'; import os from 'node:os'; import path from 'node:path'; import {spawn,spawnSync} from 'node:child_process'; import test from 'node:test';
const root=path.resolve(import.meta.dirname,'..'), enabled=process.env.BDF_RUN_M014_DB_REHEARSAL==='1', pgBin=process.env.BDF_PG_BIN;
const env={...process.env,LANG:'C',LC_ALL:'C',PGCLIENTENCODING:'UTF8',TZ:'UTC'};
const migrations=['20260806090905_m001_bdf_schemas_default_deny.sql','20260806090908_m002_bdf_source_identity_envelope.sql','20260806090911_m003_bdf_corporations_stores.sql','20260806090915_m004_bdf_departments_employees.sql','20260806090918_m005_bdf_employee_store_assignments.sql','20260806090921_m006_bdf_store_relationships_population.sql','20260806090925_m007_bdf_master_versions_audit.sql','20260806090928_m008_bdf_master_projections.sql','20260806090931_m009_bdf_rls_grants.sql','20260806090935_m010_bdf_verification_gate.sql','20260806201417_m011_bdf_snapshot_metadata_foundation.sql','20260807112029_m061_bdf_snapshot_contract_versions_nonblank.sql','20260806223721_m012_bdf_accounting_import_boundary.sql','20260807122604_m013_bdf_account_master_statement_mapping.sql','20260807211422_m062_bdf_account_hierarchy_cycle_guard.sql','20260807220334_m014_bdf_accounting_version_lifecycle.sql'];
const rollbacks=['supabase/rollback/pr002/m014_bdf_accounting_version_lifecycle.rollback.sql','supabase/rollback/pr002/m062_bdf_account_hierarchy_cycle_guard.rollback.sql','supabase/rollback/pr002/m013_bdf_account_master_statement_mapping.rollback.sql','supabase/rollback/pr002/m012_bdf_accounting_import_boundary.rollback.sql','supabase/rollback/pr001b1/m061_bdf_snapshot_contract_versions_nonblank.rollback.sql','supabase/rollback/pr001b1/m011_bdf_snapshot_metadata_foundation.rollback.sql','supabase/rollback/pr001a/m010_bdf_verification_gate.rollback.sql','supabase/rollback/pr001a/m009_bdf_rls_grants.rollback.sql','supabase/rollback/pr001a/m008_bdf_master_projections.rollback.sql','supabase/rollback/pr001a/m007_bdf_master_versions_audit.rollback.sql','supabase/rollback/pr001a/m006_bdf_store_relationships_population.rollback.sql','supabase/rollback/pr001a/m005_bdf_employee_store_assignments.rollback.sql','supabase/rollback/pr001a/m004_bdf_departments_employees.rollback.sql','supabase/rollback/pr001a/m003_bdf_corporations_stores.rollback.sql','supabase/rollback/pr001a/m002_bdf_source_identity_envelope.rollback.sql','supabase/rollback/pr001a/m001_bdf_schemas_default_deny.rollback.sql'];
function cmd(exe,args,input,allow=false){const r=spawnSync(exe,args,{cwd:root,encoding:'utf8',env,input,maxBuffer:64*1024*1024});if(!allow&&r.status!==0)throw new Error(`${exe} ${args.join(' ')}\n${r.stdout}\n${r.stderr}`);return r;}
test('M001-M014 plus M061/M062 are deterministic', {skip:!enabled&&'set BDF_RUN_M014_DB_REHEARSAL=1',timeout:480000}, async()=>{
 assert.ok(pgBin);const dir=await mkdtemp(path.join(os.tmpdir(),'bdf-m014-pg17-'));const port=57500+(process.pid%400),exe=n=>path.join(pgBin,`${n}.exe`);let started=false;
 const psql=sql=>cmd(exe('psql'),['-X','-v','ON_ERROR_STOP=1','-At','-h','127.0.0.1','-p',String(port),'-U','postgres','-d','bdf_m014'],sql),file=p=>readFile(path.join(root,p),'utf8');
 const apply=async()=>{for(const m of migrations)await psql(await file(`supabase/migrations/${m}`));};
 const catalog=()=>psql(`with t as(select 'r|'||n.nspname||'|'||c.relname||'|'||c.relkind::text||'|'||c.relrowsecurity::text||'|'||c.relforcerowsecurity::text x from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname in('core','governance','projection','accounting') union all select 'c|'||n.nspname||'|'||c.relname||'|'||q.conname||'|'||pg_get_constraintdef(q.oid) from pg_constraint q join pg_class c on c.oid=q.conrelid join pg_namespace n on n.oid=c.relnamespace where n.nspname in('core','governance','projection','accounting') union all select 'f|'||n.nspname||'|'||p.proname||'|'||pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname in('core','governance','projection','accounting'))select x from t order by x;`).stdout;
 try{cmd(exe('initdb'),['-D',dir,'-U','postgres','-A','trust','--encoding=UTF8','--locale=C']);const server=spawn(exe('postgres'),['-D',dir,'-p',String(port),'-h','127.0.0.1'],{detached:true,env,stdio:'ignore',windowsHide:true});server.unref();for(let i=0;i<80;i++){if(cmd(exe('pg_isready'),['-h','127.0.0.1','-p',String(port),'-U','postgres'],undefined,true).status===0){started=true;break;}await new Promise(r=>setTimeout(r,250));}assert.ok(started);cmd(exe('createdb'),['-h','127.0.0.1','-p',String(port),'-U','postgres','-T','template0','-E','UTF8','--locale=C','bdf_m014']);psql('create schema extensions;create role anon nologin;create role authenticated nologin;create role service_role nologin;');
 await apply();await psql(await file('supabase/validation/pr002/validate_m014.sql'));await psql(await file('supabase/validation/pr002/test_m014_accounting_version_lifecycle.sql'));await psql(await file('supabase/validation/pr002/test_m013_account_mapping.sql'));await psql(await file('supabase/validation/pr002/test_m062_account_hierarchy_cycle.sql'));const first=catalog(),hash=createHash('sha256').update(first).digest('hex');
 await psql(await file(rollbacks[0]));assert.equal(psql("select count(*) from information_schema.tables where table_schema='accounting' and table_name in('scenario_contracts','measure_type_contracts','accounting_versions');").stdout.trim(),'0');assert.equal(psql("select count(*) from information_schema.tables where table_schema='accounting' and table_name in('account_identities','accounts','account_statement_mappings');").stdout.trim(),'3');await psql(await file(`supabase/migrations/${migrations.at(-1)}`));assert.equal(createHash('sha256').update(catalog()).digest('hex'),hash);
 for(const rb of rollbacks)await psql(await file(rb));assert.equal(psql("select count(*) from pg_namespace where nspname in('core','governance','projection','accounting');").stdout.trim(),'0');await apply();await psql(await file('supabase/validation/pr002/validate_m014.sql'));await psql(await file('supabase/validation/pr002/test_m014_accounting_version_lifecycle.sql'));assert.equal(createHash('sha256').update(catalog()).digest('hex'),hash);process.stdout.write(`BDF_M014_REHEARSAL_PASS forward=16 rollback=16 reapply=16 catalog=${hash}\n`);
 }finally{if(started)cmd(exe('pg_ctl'),['-D',dir,'-m','immediate','-w','stop'],undefined,true);await rm(dir,{recursive:true,force:true});}
});
