import assert from "node:assert/strict";import{spawn,spawnSync}from"node:child_process";import{mkdtemp,readFile,rm}from"node:fs/promises";import os from"node:os";import path from"node:path";import test from"node:test";
const root=path.resolve(import.meta.dirname,".."),enabled=process.env.NOV_TALENT_RUN_RECRUITING_PLANNING_DB_TEST==="1",pgBin=process.env.NOV_TALENT_PG_BIN,env={...process.env,LANG:"C",LC_ALL:"C",PGCLIENTENCODING:"UTF8",TZ:"UTC"};
function cmd(exe,args,input,allow=false){const r=spawnSync(exe,args,{cwd:root,encoding:"utf8",env,input,maxBuffer:32*1024*1024,windowsHide:true});if(!allow&&r.status!==0)throw new Error(`${exe} ${args.join(" ")}\n${r.stdout}\n${r.stderr}`);return r;}
test("Recruiting Planning forward migration is atomic and RPC-only on Fresh PostgreSQL 17",{skip:!enabled&&"set NOV_TALENT_RUN_RECRUITING_PLANNING_DB_TEST=1",timeout:240000},async()=>{
 assert.ok(pgBin);const base=await readFile(path.join(root,"supabase/migrations/20260811050625_nov_talent_recruiting_target_foundation.sql"),"utf8"),migration=await readFile(path.join(root,"supabase/migrations/20260811055113_nov_talent_recruiting_planning_foundation.sql"),"utf8"),rollback=await readFile(path.join(root,"supabase/migrations/review_only/20260811055113_nov_talent_recruiting_planning_foundation.rollback.sql"),"utf8");
 const dir=await mkdtemp(path.join(os.tmpdir(),"nov-planning-pg17-")),port=59800+(process.pid%100),exe=n=>path.join(pgBin,`${n}.exe`);let started=false;const psql=(sql,allow=false)=>cmd(exe("psql"),["-X","-v","ON_ERROR_STOP=1","-At","-h","127.0.0.1","-p",String(port),"-U","postgres","-d","planning"],sql,allow);
 try{cmd(exe("initdb"),["-D",dir,"-U","postgres","-A","trust","--encoding=SQL_ASCII","--locale=C"]);const s=spawn(exe("postgres"),["-D",dir,"-p",String(port),"-h","127.0.0.1"],{detached:true,env,stdio:"ignore",windowsHide:true});s.unref();for(let i=0;i<80;i++){if(cmd(exe("pg_isready"),["-h","127.0.0.1","-p",String(port),"-U","postgres"],undefined,true).status===0){started=true;break}await new Promise(r=>setTimeout(r,250))}assert.ok(started);cmd(exe("createdb"),["-h","127.0.0.1","-p",String(port),"-U","postgres","-T","template0","-E","UTF8","--locale=C","planning"]);psql("create role anon nologin;create role authenticated nologin;create role service_role nologin bypassrls;");psql(base);psql(migration);psql(rollback);assert.equal(psql("select to_regclass('public.nov_talent_recruiting_targets_v1') is not null;select to_regclass('public.nov_talent_recruiting_funnel_targets_v1') is null;").stdout.trim().replaceAll("\r",""),"t\nt");psql(migration);
 assert.equal(psql("select count(*) from public.nov_talent_recruiting_targets_v1;select relrowsecurity::text||'|'||relforcerowsecurity::text from pg_class where oid='public.nov_talent_recruiting_funnel_targets_v1'::regclass;select has_table_privilege('service_role','public.nov_talent_recruiting_budgets_v1','select')::text||'|'||has_table_privilege('service_role','public.nov_talent_recruiting_budgets_v1','insert')::text;").stdout.trim().replaceAll("\r",""),"0\ntrue|true\ntrue|false");
 const actor="00000000-0000-4000-8000-000000000009";const out=psql(`do $t$ declare t1 uuid;t2 uuid;b uuid;begin
 select target_id into t1 from public.nov_talent_create_planning_target_draft_v1('${actor}','hr.admin','NEW_GRAD',2028,'APPLICATION_COUNT','FY2028','2027-04-01','2028-03-31',45,'2026-08-11','2028-03-31','Approved plan');perform * from public.nov_talent_approve_planning_target_v1('${actor}','hr.admin',t1,1);
 select target_id into t2 from public.nov_talent_create_planning_target_draft_v1('${actor}','hr.admin','NEW_GRAD',2028,'APPLICATION_COUNT','FY2028','2027-04-01','2028-03-31',46,'2026-08-11','2028-03-31','Revision');begin perform * from public.nov_talent_approve_planning_target_v1('${actor}','hr.admin',t2,99);raise exception 'stale';exception when sqlstate '40001' then null;end;perform * from public.nov_talent_approve_planning_target_v1('${actor}','hr.admin',t2,1);
 begin perform * from public.nov_talent_create_planning_target_draft_v1('${actor}','hr.admin','NEW_GRAD',2028,'EXPECTED_JOIN_COUNT','FY2028','2027-04-01','2028-03-31',1,'2026-08-11','2028-03-31','Reserved');raise exception 'expected_join';exception when sqlstate '22023' then null;end;
 select budget_id into b from public.nov_talent_create_planning_budget_draft_v1('${actor}','hr.admin','MID_CAREER',null,'FY2026','2026-04-01','2027-03-31',2400000,'JPY','2026-08-11','2027-03-31','Annual budget','[{"channelCode":"OWNED_WEB","amount":500000,"reason":"HP"},{"channelCode":"PAID_JOB_MEDIA","amount":1400000,"reason":"Media"},{"channelCode":"SNS","amount":500000,"reason":"SNS"}]');perform * from public.nov_talent_approve_planning_budget_v1('${actor}','hr.admin',b,1);
 begin update public.nov_talent_recruiting_budgets_v1 set total_budget=1 where budget_id=b;raise exception 'immutable';exception when sqlstate '55000' then null;end;
 begin update public.nov_talent_recruiting_budget_audit_v1 set actor_role='backoffice';raise exception 'audit_mutable';exception when sqlstate '55000' then null;end;
end$t$;set role service_role;do $s$ begin begin insert into public.nov_talent_recruiting_funnel_targets_v1(recruiting_track,graduation_year,target_metric,recruiting_period_code,recruiting_period_start,recruiting_period_end,scope_type,target_count,version,record_state,effective_from,effective_to,reason,created_by)values('NEW_GRAD',2028,'CONTACT_COUNT','X','2026-01-01','2026-12-31','COMPANY',1,1,'DRAFT','2026-01-01','2026-12-31','No','${actor}');raise exception 'direct';exception when sqlstate '42501' then null;end;end$s$;reset role;select (select count(*) from public.nov_talent_recruiting_funnel_targets_v1)||'|'||(select count(*) from public.nov_talent_recruiting_budgets_v1)||'|'||(select count(*) from public.nov_talent_recruiting_budget_lines_v1)||'|'||(select count(*) from public.nov_talent_recruiting_targets_v1);`).stdout.trim().replaceAll("\r","").split("\n").at(-1);assert.equal(out,"2|1|3|0");
 const guarded=psql(rollback,true);assert.notEqual(guarded.status,0);assert.match(`${guarded.stdout}${guarded.stderr}`,/RECRUITING_PLANNING_ROLLBACK_REQUIRES_EMPTY_TABLES/);
 }finally{if(started)cmd(exe("pg_ctl"),["-D",dir,"stop","-m","immediate"],undefined,true);await rm(dir,{recursive:true,force:true});}
});
