import assert from "node:assert/strict"; import { spawn, spawnSync } from "node:child_process"; import { mkdtemp, readFile, rm } from "node:fs/promises"; import os from "node:os"; import path from "node:path"; import test from "node:test";
const root=path.resolve(import.meta.dirname,".."), enabled=process.env.NOV_TALENT_RUN_RECRUITING_ACTUAL_DB_TEST==="1", pgBin=process.env.NOV_TALENT_PG_BIN, env={...process.env,LANG:"C",LC_ALL:"C",PGCLIENTENCODING:"UTF8",TZ:"UTC"};
function cmd(exe,args,input,allow=false){const r=spawnSync(exe,args,{cwd:root,encoding:"utf8",env,input,maxBuffer:32*1024*1024,windowsHide:true});if(!allow&&r.status!==0)throw new Error(`${exe} ${args.join(" ")}\n${r.stdout}\n${r.stderr}`);return r;}
test("Actual Fact candidate migration is additive, forced-RLS, append-only and RPC-only on Fresh PostgreSQL 17",{skip:!enabled&&"set NOV_TALENT_RUN_RECRUITING_ACTUAL_DB_TEST=1",timeout:240000},async()=>{
 assert.ok(pgBin); const migration=await readFile(path.join(root,"supabase/migrations/20260811224534_nov_talent_recruiting_actual_fact_foundation.sql"),"utf8");
 const dir=await mkdtemp(path.join(os.tmpdir(),"nov-actual-pg17-")),port=59900+(process.pid%80),exe=n=>path.join(pgBin,`${n}.exe`);let started=false;const psql=(sql,allow=false)=>cmd(exe("psql"),["-X","-v","ON_ERROR_STOP=1","-At","-h","127.0.0.1","-p",String(port),"-U","postgres","-d","actual"],sql,allow);
 try{cmd(exe("initdb"),["-D",dir,"-U","postgres","-A","trust","--encoding=SQL_ASCII","--locale=C"]);const s=spawn(exe("postgres"),["-D",dir,"-p",String(port),"-h","127.0.0.1"],{detached:true,env,stdio:"ignore",windowsHide:true});s.unref();for(let i=0;i<80;i++){if(cmd(exe("pg_isready"),["-h","127.0.0.1","-p",String(port),"-U","postgres"],undefined,true).status===0){started=true;break}await new Promise(r=>setTimeout(r,250))}assert.ok(started);cmd(exe("createdb"),["-h","127.0.0.1","-p",String(port),"-U","postgres","-T","template0","-E","UTF8","--locale=C","actual"]);
 psql("create role anon nologin;create role authenticated nologin;create role service_role nologin bypassrls;create table public.nov_talent_candidates_v1(candidate_id uuid primary key);");psql(migration);
 const actor="00000000-0000-4000-8000-000000000009",candidate="00000000-0000-4000-8000-000000000001",store="00000000-0000-4000-8000-000000000002",company="00000000-0000-4000-8000-000000000003";psql(`insert into public.nov_talent_candidates_v1 values('${candidate}');
 do $t$ declare e uuid;s uuid;begin
  select engagement_fact_id into e from public.nov_talent_append_recruiting_engagement_fact_v1('${actor}','hr.admin','${candidate}','CONTACT','2026-05-01T00:00:00Z',null,'COMPLETED','MANUAL_REVIEW','contact-1',repeat('a',64));
  perform * from public.nov_talent_append_recruiting_engagement_fact_v1('${actor}','hr.admin','${candidate}','SALON_VISIT','2026-06-01T00:00:00Z','${store}','COMPLETED','MANUAL_REVIEW','visit-1',repeat('b',64));
  begin perform * from public.nov_talent_append_recruiting_engagement_fact_v1('${actor}','employee','${candidate}','CONTACT','2026-05-02T00:00:00Z',null,'COMPLETED','MANUAL_REVIEW','contact-x',repeat('c',64));raise exception 'unauthorized';exception when sqlstate '42501' then null;end;
  begin perform * from public.nov_talent_append_recruiting_engagement_fact_v1('${actor}','hr.admin','${candidate}','SALON_VISIT','2026-06-02T00:00:00Z',null,'COMPLETED','MANUAL_REVIEW','visit-x',repeat('d',64));raise exception 'missing_store';exception when check_violation then null;end;
  select spend_fact_id into s from public.nov_talent_append_recruiting_spend_fact_v1('${actor}','hr.admin','NEW_GRAD',2027,'2026-04-01','2027-03-31','${company}','JOB_FAIR','JOB_FAIR',748000,'2026-05-01','PROVISIONAL','DEPARTMENT_LEDGER','fair-1',repeat('e',64));
  perform * from public.nov_talent_append_recruiting_spend_fact_v1('${actor}','hr.admin','NEW_GRAD',2027,'2026-04-01','2027-03-31','${company}','JOB_FAIR','JOB_FAIR',748000,'2026-05-01','VOIDED','DEPARTMENT_LEDGER','fair-1-void',repeat('f',64),s,'Accounting not confirmed');
  begin update public.nov_talent_recruiting_engagement_facts_v1 set source_reference='changed' where engagement_fact_id=e;raise exception 'mutable';exception when sqlstate '55000' then null;end;
 end$t$;`);
 assert.equal(psql("select count(*)||'|'||(select count(*) from public.nov_talent_recruiting_engagement_audit_v1)||'|'||(select count(*) from public.nov_talent_recruiting_spend_facts_v1)||'|'||(select count(*) from public.nov_talent_recruiting_spend_audit_v1) from public.nov_talent_recruiting_engagement_facts_v1;").stdout.trim(),"2|2|2|2");
 assert.equal(psql("select count(*) from public.nov_talent_candidates_v1;").stdout.trim(),"1");
 assert.equal(psql("select count(*) from pg_class where relname like 'nov_talent_%' and relkind='r' and relrowsecurity and relforcerowsecurity;").stdout.trim(),"6");
 const direct=psql(`set role service_role;insert into public.nov_talent_recruiting_engagement_facts_v1(candidate_id,engagement_type,occurred_at,engagement_status,source_type,source_reference,source_fingerprint,actor_employee_id)values('${candidate}','CONTACT',now(),'COMPLETED','X','X',repeat('0',64),'${actor}');`,true);assert.notEqual(direct.status,0);assert.match(`${direct.stdout}${direct.stderr}`,/permission denied|row-level security/i);
 }finally{if(started)cmd(exe("pg_ctl"),["-D",dir,"stop","-m","immediate"],undefined,true);await rm(dir,{recursive:true,force:true});}
});
