import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { createHandler } from "../supabase/functions/nov-talent-staging-api/index.ts";
import { ACTUAL_SOURCE, cleanPlanningBudgetDraft, cleanPlanningTargetDraft, RECRUITING_PLANNING_CONTRACT_VERSION } from "../supabase/functions/nov-talent-staging-api/recruiting-planning-v1.ts";
const A="10000000-0000-4000-8000-000000000001",T="20000000-0000-4000-8000-000000000001";
const req=(path,method="GET",body)=>new Request(`https://staging.invalid/functions/v1/nov-talent-staging-api${path}`,{method,headers:{origin:"https://ideanow-shift.github.io",authorization:`Bearer ${"a".repeat(32)}`,...(body?{"content-type":"application/json"}:{})},...(body?{body:JSON.stringify(body)}:{})});
function fixture(enabled=false,role="hr.admin"){const calls=[];return{calls,handler:createHandler({hubApiUrl:"https://hub.invalid",supabaseUrl:"https://staging.invalid",serviceRoleKey:"x",recruitingPlanningWritesEnabled:enabled,fetchImpl:async(url,init={})=>{const s=String(url);calls.push({s,body:init.body&&JSON.parse(String(init.body))});if(s==="https://hub.invalid")return Response.json({ok:true,employee:{id:A,roleKeys:[role]}});if(s.includes("/rest/v1/nov_talent_recruiting_"))return Response.json([]);if(s.includes("/rpc/nov_talent_create_planning_target"))return Response.json([{target_id:T,recruiting_track:"NEW_GRAD",graduation_year:2028,target_metric:"APPLICATION_COUNT",recruiting_period_code:"FY2028",recruiting_period_start:"2027-04-01",recruiting_period_end:"2028-03-31",target_count:45,version:1,row_version:1,record_state:"DRAFT",effective_from:"2026-08-11",effective_to:"2028-03-31",reason:"Owner approved",approved_at:null}]);return Response.json({}, {status:400});}})}}
const target=(extra={})=>({recruitingTrack:"NEW_GRAD",graduationYear:2028,targetMetric:"APPLICATION_COUNT",periodCode:"FY2028",periodStart:"2027-04-01",periodEnd:"2028-03-31",targetCount:45,effectiveFrom:"2026-08-11",effectiveTo:"2028-03-31",reason:"Owner approved",...extra});
const budget=(extra={})=>({recruitingTrack:"MID_CAREER",graduationYear:null,periodCode:"FY2026",periodStart:"2026-04-01",periodEnd:"2027-03-31",totalBudget:2400000,currency:"JPY",effectiveFrom:"2026-08-11",effectiveTo:"2027-03-31",reason:"Owner approved",lines:[{channelCode:"OWNED_WEB",amount:500000,reason:"Annual plan"},{channelCode:"PAID_JOB_MEDIA",amount:1400000,reason:"Annual plan"},{channelCode:"SNS",amount:500000,reason:"Annual plan"}],...extra});
test("Planning 1.1 track, metric, actual-source and channel boundaries",()=>{assert.equal(RECRUITING_PLANNING_CONTRACT_VERSION,"1.1.0");assert.equal(cleanPlanningTargetDraft(target({targetCount:0})).targetCount,0);assert.equal(cleanPlanningTargetDraft(target({targetMetric:"EXPECTED_JOIN_COUNT"})),null);assert.equal(cleanPlanningTargetDraft(target({recruitingTrack:"MID_CAREER",graduationYear:2028})),null);assert.ok(cleanPlanningBudgetDraft(budget()));assert.equal(cleanPlanningBudgetDraft(budget({currency:"USD"})),null);assert.equal(ACTUAL_SOURCE.CONTACT_COUNT,"ACTUAL_SOURCE_UNAVAILABLE");assert.equal(ACTUAL_SOURCE.APPLICATION_COUNT,"SELECTION_HISTORY:APPLICATION_RECEIVED");});
test("Migration is forward-only, forced-RLS and preserves #102",async()=>{const sql=await readFile(new URL("../supabase/migrations/20260811055113_nov_talent_recruiting_planning_foundation.sql",import.meta.url),"utf8");assert.match(sql,/create table public\.nov_talent_recruiting_funnel_targets_v1/i);assert.match(sql,/create table public\.nov_talent_recruiting_budgets_v1/i);assert.match(sql,/create table public\.nov_talent_recruiting_budget_lines_v1/i);assert.equal((sql.match(/force row level security/gi)||[]).length,5);assert.match(sql,/grant execute on function public\.nov_talent_approve_planning_target_v1[^;]+service_role/i);assert.doesNotMatch(sql,/alter table public\.nov_talent_recruiting_targets_v1/i);assert.doesNotMatch(sql,/alter table public\.nov_talent_(candidates|selection_history|communications|next_actions|candidate_fair)/i);});
test("2026 fixture never maps ambiguous hiring labels",async()=>{const f=JSON.parse(await readFile(new URL("./fixtures/nov-talent-recruiting-planning-2026.json",import.meta.url),"utf8"));assert.deepEqual(f.newGrad.targets,{CONTACT_COUNT:563,SALON_VISIT_COUNT:112,APPLICATION_COUNT:45});assert.equal(f.newGrad.budget.total,7385350);assert.equal(f.newGrad.unresolvedLabels[0].resolution,"HUMAN_REVIEW_REQUIRED");assert.equal(f.midCareer.graduationYear,null);assert.equal(Object.values(f.midCareer.budget.lines).reduce((a,b)=>a+b,0),2400000);assert.equal(f.midCareer.unresolvedLabels[0].resolution,"HUMAN_REVIEW_REQUIRED");});
test("read is admin-only/read-only and write flag defaults off",async()=>{const run=fixture();const r=await run.handler(req("/api/talent/v1/recruiting-planning/current"));assert.equal(r.status,200);const body=await r.json();assert.equal(body.data.recruiting_planning_contract_version,"1.1.0");assert.equal(run.calls.some(x=>x.s.includes("/rpc/")),false);assert.equal((await fixture(false,"general").handler(req("/api/talent/v1/recruiting-planning/current"))).status,403);assert.equal((await run.handler(req("/api/talent/v1/recruiting-planning/targets/drafts","POST",target()))).status,503);});
test("runtime capability combines authenticated session, Planning role and Edge flag",async()=>{
  const off=await fixture(false,"hr.admin").handler(req("/api/talent/v1/recruiting-planning/capability"));
  assert.equal(off.status,200);assert.equal((await off.json()).data.canWritePlanning,false);
  const on=await fixture(true,"hr.admin").handler(req("/api/talent/v1/recruiting-planning/capability"));
  assert.equal(on.status,200);assert.equal((await on.json()).data.canWritePlanning,true);
  const unauthorized=await fixture(true,"executive").handler(req("/api/talent/v1/recruiting-planning/capability"));
  assert.equal(unauthorized.status,200);assert.equal((await unauthorized.json()).data.canWritePlanning,false);
  const missing=new Request("https://staging.invalid/functions/v1/nov-talent-staging-api/api/talent/v1/recruiting-planning/capability",{headers:{origin:"https://ideanow-shift.github.io"}});
  assert.equal((await fixture(true).handler(missing)).status,401);
});
test("enabled command resolves actor only server-side",async()=>{const run=fixture(true);const r=await run.handler(req("/api/talent/v1/recruiting-planning/targets/drafts","POST",target()));assert.equal(r.status,201);const call=run.calls.find(x=>x.s.includes("/rpc/nov_talent_create_planning_target"));assert.equal(call.body.p_actor_employee_id,A);assert.equal(call.body.p_actor_role,"hr.admin");assert.equal(cleanPlanningTargetDraft({...target(),actorEmployeeId:A}),null);});
