import test from "node:test";
import assert from "node:assert/strict";

process.env.NODE_ENV="test";
const {createStoreOperationsStagingServer}=await import("../deploy/store-operations-staging-ui/server.mjs");
const serviceAccount="runtime@staging.example.iam.gserviceaccount.com";

async function withServer(edgeFetch,run,overrides={}){
  const metadataFetch=async(url)=>new Response(String(url).includes("/email")?serviceAccount:"header.payload.signature");
  const server=createStoreOperationsStagingServer({edgeFetch,metadataFetch,exchangeSecret:"server-boundary-secret-with-32-bytes-minimum",cookieSigningSecret:"cookie-signing-secret-with-32-bytes-minimum",launcherUrl:"https://staging-hub.example/",expectedRuntimeServiceAccount:serviceAccount,edgeUrl:"https://edge.invalid/nov-hub-api",...overrides});
  await new Promise(resolve=>server.listen(0,"127.0.0.1",resolve));
  try{const address=server.address();await run(`http://127.0.0.1:${address.port}`);}finally{await new Promise((resolve,reject)=>server.close(error=>error?reject(error):resolve()));}
}

async function start(origin){const response=await fetch(`${origin}/auth/start`,{redirect:"manual"});assert.equal(response.status,302);const location=new URL(response.headers.get("location"));assert.equal(location.searchParams.get("code_challenge_method"),"S256");assert.match(location.searchParams.get("code_challenge")||"",/^[A-Za-z0-9_-]{43}$/u);assert.equal(location.searchParams.get("callback_path"),"/auth/callback");return {cookie:(response.headers.get("set-cookie")||"").split(";")[0],state:location.searchParams.get("store_operations_state")};}

test("/auth/start creates signed HttpOnly PKCE state without Domain",async()=>{await withServer(async()=>{throw new Error("edge must not be called");},async(origin)=>{const response=await fetch(`${origin}/auth/start`,{redirect:"manual"});const cookie=response.headers.get("set-cookie")||"";assert.match(cookie,/__Host-store_ops_handoff=/u);assert.match(cookie,/Secure; HttpOnly; SameSite=Lax/u);assert.doesNotMatch(cookie,/Domain=/iu);assert.equal(response.headers.get("cache-control"),"no-store");assert.equal(response.headers.get("referrer-policy"),"no-referrer");});});

test("BFF exchanges opaque code with PKCE and Google service identity",async()=>{const calls=[];await withServer(async(url,init)=>{calls.push({url,init,body:JSON.parse(init.body)});return Response.json({ok:true,session:{sessionToken:"private-app-session",expiresAt:new Date(Date.now()+600000).toISOString()}});},async(origin)=>{const launched=await start(origin);const response=await fetch(`${origin}/session/handoff/exchange`,{method:"POST",headers:{"content-type":"application/json",cookie:launched.cookie},body:JSON.stringify({handoffCode:"A".repeat(43),state:launched.state})});assert.equal(response.status,200);assert.doesNotMatch(await response.text(),/private-app-session/u);assert.match(response.headers.get("set-cookie")||"",/__Host-store_ops_session=.*Secure; HttpOnly; SameSite=Lax/u);});assert.equal(calls.length,1);assert.equal(calls[0].body.action,"storeOperationsHandoffExchangeV1");assert.match(calls[0].body.payload.codeVerifier,/^[A-Za-z0-9_-]{43}$/u);assert.match(calls[0].init.headers["x-cloud-run-identity"],/^Bearer header\.payload\.signature$/u);assert.equal(calls[0].init.headers["x-store-operations-exchange-secret"],"server-boundary-secret-with-32-bytes-minimum");assert.equal("authorization" in calls[0].init.headers,false);});

test("BFF rejects missing signed start state and wrong state",async()=>{await withServer(async()=>{throw new Error("edge must not be called");},async(origin)=>{const missing=await fetch(`${origin}/session/handoff/exchange`,{method:"POST",body:"{}"});assert.equal(missing.status,401);const launched=await start(origin);const wrong=await fetch(`${origin}/session/handoff/exchange`,{method:"POST",headers:{"content-type":"application/json",cookie:launched.cookie},body:JSON.stringify({handoffCode:"A".repeat(43),state:`${launched.state}x`})});assert.equal(wrong.status,401);});});

test("BFF ignores browser authority and forwards only read-only projection",async()=>{const calls=[];await withServer(async(url,init)=>{calls.push(JSON.parse(init.body));return Response.json({ok:true,projection:{dataState:"preparing"}});},async(origin)=>{const response=await fetch(`${origin}/api/store-operations`,{method:"POST",headers:{"content-type":"application/json",cookie:"__Host-store_ops_session=private-app-session"},body:JSON.stringify({action:"storeMonthlyActualProjectionV1",payload:{selectedMonth:"2026-06",role:"executive",scope:"all",employeeId:"spoof",storeId:"spoof"}})});assert.equal(response.status,200);});assert.deepEqual(calls[0],{action:"storeMonthlyActualProjectionV1",payload:{selectedMonth:"2026-06",authType:"store_operations_staging_session",responseProfile:""}});});

test("BFF fails closed without OIDC configuration and defense secret",async()=>{await withServer(async()=>{throw new Error("must not call edge");},async(origin)=>{const response=await fetch(`${origin}/session/handoff/exchange`,{method:"POST",body:"{}"});assert.equal(response.status,503);},{exchangeSecret:""});await withServer(async()=>{throw new Error("must not call edge");},async(origin)=>{const launched=await start(origin);const response=await fetch(`${origin}/session/handoff/exchange`,{method:"POST",headers:{cookie:launched.cookie,"content-type":"application/json"},body:JSON.stringify({handoffCode:"A".repeat(43),state:launched.state})});assert.equal(response.status,503);assert.equal((await response.json()).code,"CLOUD_RUN_IDENTITY_MISMATCH");},{expectedRuntimeServiceAccount:""});});
