import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { resolve } from "node:path";

const root = resolve(import.meta.dirname, "../docs/store_sales_staging_provisioning");
const inventory = await readFile(resolve(root, "staging-environment-inventory.md"), "utf8");
const project = await readFile(resolve(root, "staging-project-decision.md"), "utf8");
const comparison = await readFile(resolve(root, "staging-project-options-comparison.md"), "utf8");
const secrets = await readFile(resolve(root, "secret-inventory.md"), "utf8");
const board = await readFile(resolve(root, "human-action-board.md"), "utf8");
const summary = await readFile(resolve(root, "final-summary.md"), "utf8");
const sandbox = await readFile(resolve(root, "sandbox_inventory.md"), "utf8");
const cleanup = await readFile(resolve(root, "cleanup_plan.md"), "utf8");
const reuse = await readFile(resolve(root, "reuse_readiness.md"), "utf8");
const build = await readFile(resolve(root, "staging_build_report.md"), "utf8");
const checklist = await readFile(resolve(root, "deployment_checklist.md"), "utf8");
const connection = await readFile(resolve(root, "staging_connection_report.md"), "utf8");
const goNoGo = await readFile(resolve(root, "go_no_go.md"), "utf8");
const secretRequirements = await readFile(resolve(root, "environment-secret-requirements.md"), "utf8");
const secretGuide = await readFile(resolve(root, "environment-secret-registration-guide.md"), "utf8");
const dataSource = await readFile(resolve(root, "data-source-decision.md"), "utf8");
const verifier = await readFile(resolve(root, "hub-session-verifier-contract.md"), "utf8");
const storeMasterPort = await readFile(resolve(root, "store-master-readonly-port-contract.md"), "utf8");
const accountingPort = await readFile(resolve(root, "accounting-readonly-port-contract.md"), "utf8");
const bindingSummary = await readFile(resolve(root, "binding-sprint-summary.md"), "utf8");

assert.match(inventory, /not selectable by inference/);
assert.match(project, /Decision pending options comparison/);
assert.match(comparison, /A\. New Staging project/);
assert.match(comparison, /B1\. Existing ACTIVE Core project/);
assert.match(comparison, /B2\. Existing INACTIVE sandbox project/);
assert.match(comparison, /Decision pending human evidence/);
assert.match(secrets, /Required secrets now: 0/);
assert.match(secrets, /Protected configuration and approval entries: 4/);
assert.match(board, /\| 7\. Approve and execute one deploy\/E2E window/);
assert.match(summary, /CONDITIONAL PASS/);
assert.match(sandbox, /Deployed Functions \| `0`/);
assert.match(sandbox, /Registered Secret names \| `0`/);
assert.match(sandbox, /not verified/);
assert.match(cleanup, /no Function deletion/);
assert.match(reuse, /# Reuse possible/);
assert.match(build, /actual runtime build cannot begin/);
assert.match(checklist, /Store Master total is not exactly 20/);
assert.match(connection, /No connection executed/);
assert.match(goNoGo, /# NO-GO/);
assert.match(secretRequirements, /Required GitHub Environment Secrets now: 0/);
assert.match(secretRequirements, /not registerable yet/);
assert.match(secretGuide, /Do not register a GitHub or Supabase secret now/);
assert.match(dataSource, /Recommended option: B/);
assert.match(dataSource, /Human approval required/);
assert.match(verifier, /AM_SCOPE_UNASSIGNED/);
assert.match(storeMasterPort, /exactly 20 active current stores: Direct 13 and FC 7/);
assert.match(accountingPort, /all profit-derived numeric fields are `null`/);
assert.match(bindingSummary, /CONDITIONAL PASS/);
assert.doesNotMatch(`${inventory}\n${project}\n${comparison}\n${secrets}\n${board}\n${summary}\n${sandbox}\n${cleanup}\n${reuse}\n${build}\n${checklist}\n${connection}\n${goNoGo}\n${secretRequirements}\n${secretGuide}\n${dataSource}\n${verifier}\n${storeMasterPort}\n${accountingPort}\n${bindingSummary}`, /postgres(?:ql)?:\/\/[^\s]+|sb_secret_[^\s]+|zgkoofphhivesclehrom/i);
process.stdout.write("RESULT staging provisioning, sandbox build gate, exact secret inventory, and binding contracts are safe and static PASS\n");
