import test from "node:test";
import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {issueStoreOperationsHandoff,exchangeStoreOperationsHandoff,STORE_OPERATIONS_HANDOFF} from "../supabase/functions/nov-hub-api/store_operations_session_handoff.mjs";

function fixture(){let now=Date.parse("2026-08-23T01:00:00Z");const rows=[];let resolveCount=0;return {rows,get resolveCount(){return resolveCount;},advance(ms){now+=ms;},deps:{now:()=>now,randomUuid:()=>crypto.randomUUID(),verifyExchangeBoundary:value=>value==="server-proof",resolveAccess:async({employeeId})=>{resolveCount++;return employeeId?{employeeId,roleKeys:["executive"],scope:{mode:"all",storeIds:Array(20).fill("store")}}:null;},signSession:async()=>"signed-store-operations-session",store:{async insert(row){rows.push(row);},async consumeAtomic(match){const row=rows.find(item=>item.codeHash===match.codeHash&&item.stateHash===match.stateHash&&item.nonceHash===match.nonceHash&&item.target===match.target&&item.targetOrigin===match.targetOrigin&&item.audience===match.audience&&!item.consumedAt&&item.expiresAt>match.now);if(!row)return null;row.consumedAt=match.now;return row;}}}};}

test("handoff is short-lived, target-bound, single-use and re-resolves access",async()=>{const f=fixture();const state="state_1234567890123456789012";const issued=await issueStoreOperationsHandoff({hubIdentity:{employeeId:crypto.randomUUID(),sessionId:crypto.randomUUID(),expiresAt:"2026-08-23T01:15:00Z"},state,target:STORE_OPERATIONS_HANDOFF.target,targetOrigin:STORE_OPERATIONS_HANDOFF.targetOrigin},f.deps);assert.match(issued.handoffCode,/^[A-Za-z0-9_-]{43}$/u);assert.equal(f.rows[0].codeHash.includes(issued.handoffCode),false);const exchanged=await exchangeStoreOperationsHandoff({exchangeProof:"server-proof",origin:STORE_OPERATIONS_HANDOFF.targetOrigin,handoffCode:issued.handoffCode,state},f.deps);assert.equal(exchanged.sessionToken,"signed-store-operations-session");assert.equal(f.resolveCount,2);await assert.rejects(()=>exchangeStoreOperationsHandoff({exchangeProof:"server-proof",origin:STORE_OPERATIONS_HANDOFF.targetOrigin,handoffCode:issued.handoffCode,state},f.deps),error=>error.code==="HANDOFF_REJECTED");});

test("exchange rejects browser calls, origin mismatch, state mismatch and expired source",async()=>{const f=fixture();const state="state_1234567890123456789012";const issued=await issueStoreOperationsHandoff({hubIdentity:{employeeId:crypto.randomUUID(),sessionId:crypto.randomUUID(),expiresAt:"2026-08-23T01:15:00Z"},state,target:STORE_OPERATIONS_HANDOFF.target,targetOrigin:STORE_OPERATIONS_HANDOFF.targetOrigin},f.deps);for(const input of [{exchangeProof:"",origin:STORE_OPERATIONS_HANDOFF.targetOrigin,state},{exchangeProof:"server-proof",origin:"https://evil.invalid",state},{exchangeProof:"server-proof",origin:STORE_OPERATIONS_HANDOFF.targetOrigin,state:`${state}x`}])await assert.rejects(()=>exchangeStoreOperationsHandoff({...input,handoffCode:issued.handoffCode},f.deps));});

test("browser and BFF source expose no raw NOV HUB token",()=>{const entry=readFileSync("deploy/store-operations-staging-ui/staging-handoff-entry.js","utf8");const server=readFileSync("deploy/store-operations-staging-ui/server.mjs","utf8");const launcher=readFileSync("portal/js/main.js","utf8");assert.doesNotMatch(entry,/access_token|refresh_token|sessionToken\s*:\s*body/i);assert.match(server,/HttpOnly/);assert.match(server,/x-store-operations-exchange-secret/);assert.doesNotMatch(launcher,/sessionToken.*URLSearchParams|access_token|refresh_token/i);assert.match(launcher,/handoff_code/);});

test("migration is private, atomic and browser-denied",()=>{const sql=readFileSync("supabase/migrations/20260823011845_store_operations_secure_session_handoff.sql","utf8");assert.match(sql,/force row level security/);assert.match(sql,/consumed_at is null/);assert.match(sql,/STORE_OPERATIONS_HANDOFF_SERVER_ONLY/);assert.match(sql,/revoke all on function public\.store_operations_handoff_consume_v1[\s\S]*from public,anon,authenticated/);assert.match(sql,/store_operations_uat_resolve_hub_employee_access_v1/);});
