import test from "node:test";
import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {createHash} from "node:crypto";
import {issueStoreOperationsHandoff,exchangeStoreOperationsHandoff,STORE_OPERATIONS_HANDOFF} from "../supabase/functions/nov-hub-api/store_operations_session_handoff.mjs";

const state="state_1234567890123456789012";
const verifier="v".repeat(43);
const challenge=createHash("sha256").update(verifier).digest("base64url");
const issueInput=(employeeId=crypto.randomUUID())=>({hubIdentity:{employeeId,sessionId:crypto.randomUUID(),expiresAt:"2026-08-23T01:15:00Z"},state,codeChallenge:challenge,codeChallengeMethod:"S256",target:STORE_OPERATIONS_HANDOFF.target,targetOrigin:STORE_OPERATIONS_HANDOFF.targetOrigin,callbackPath:STORE_OPERATIONS_HANDOFF.callbackPath});
const exchangeInput=(code,extra={})=>({exchangeProof:"server-proof",oidcToken:"valid-google-oidc",origin:STORE_OPERATIONS_HANDOFF.targetOrigin,handoffCode:code,state,codeVerifier:verifier,...extra});

function fixture(){let now=Date.parse("2026-08-23T01:00:00Z");const rows=[];let resolveCount=0;return {rows,get resolveCount(){return resolveCount;},advance(ms){now+=ms;},deps:{now:()=>now,randomUuid:()=>crypto.randomUUID(),verifyServerIdentity:async(value)=>{if(value!=="valid-google-oidc")throw Object.assign(new Error("OIDC_REQUIRED"),{code:"OIDC_REQUIRED"});},verifyExchangeBoundary:value=>value==="server-proof",resolveAccess:async({employeeId})=>{resolveCount++;return employeeId?{employeeId,roleKeys:["executive"],scope:{mode:"all",storeIds:Array(20).fill("store")}}:null;},signSession:async()=>"signed-store-operations-session",store:{async insert(row){rows.push(row);},async consumeAtomic(match){const row=rows.find(item=>item.codeHash===match.codeHash&&item.stateHash===match.stateHash&&item.nonceHash===match.nonceHash&&item.codeChallenge===match.codeChallenge&&item.contract===match.contract&&item.target===match.target&&item.targetOrigin===match.targetOrigin&&item.callbackPath===match.callbackPath&&item.audience===match.audience&&!item.consumedAt&&item.expiresAt>match.now);if(!row)return null;row.consumedAt=match.now;return row;}}}};}

test("PKCE S256 handoff is short-lived, target-bound, single-use and re-resolves access",async()=>{const f=fixture();const issued=await issueStoreOperationsHandoff(issueInput(),f.deps);assert.match(issued.handoffCode,/^[A-Za-z0-9_-]{43}$/u);assert.equal(f.rows[0].codeHash.includes(issued.handoffCode),false);assert.equal(f.rows[0].codeChallenge,challenge);assert.equal("codeVerifier" in f.rows[0],false);const exchanged=await exchangeStoreOperationsHandoff(exchangeInput(issued.handoffCode),f.deps);assert.equal(exchanged.sessionToken,"signed-store-operations-session");assert.equal(f.resolveCount,2);await assert.rejects(()=>exchangeStoreOperationsHandoff(exchangeInput(issued.handoffCode),f.deps),error=>error.code==="HANDOFF_REJECTED");});

test("issue rejects non-S256 and exchange rejects missing or wrong verifier",async()=>{const f=fixture();await assert.rejects(()=>issueStoreOperationsHandoff({...issueInput(),codeChallengeMethod:"plain"},f.deps),error=>error.code==="INVALID_CHALLENGE_METHOD");const issued=await issueStoreOperationsHandoff(issueInput(),f.deps);await assert.rejects(()=>exchangeStoreOperationsHandoff(exchangeInput(issued.handoffCode,{codeVerifier:""}),f.deps),error=>error.code==="PKCE_VERIFIER_REQUIRED");await assert.rejects(()=>exchangeStoreOperationsHandoff(exchangeInput(issued.handoffCode,{codeVerifier:"w".repeat(43)}),f.deps),error=>error.code==="HANDOFF_REJECTED");});

test("exchange rejects browser calls, origin mismatch and state mismatch",async()=>{for(const extra of [{oidcToken:""},{exchangeProof:""},{origin:"https://evil.invalid"},{state:`${state}x`}]){const f=fixture();const issued=await issueStoreOperationsHandoff(issueInput(),f.deps);await assert.rejects(()=>exchangeStoreOperationsHandoff(exchangeInput(issued.handoffCode,extra),f.deps));}});

test("browser and BFF source expose no raw NOV HUB token",()=>{const entry=readFileSync("deploy/store-operations-staging-ui/staging-handoff-entry.js","utf8");const server=readFileSync("deploy/store-operations-staging-ui/server.mjs","utf8");const launcher=readFileSync("deploy/nov-hub-staging-ui/app.js","utf8");const productionPortal=readFileSync("portal/js/main.js","utf8");assert.doesNotMatch(entry,/access_token|refresh_token|sessionToken\s*:\s*body/i);assert.match(server,/HttpOnly/);assert.match(server,/x-cloud-run-identity/);assert.match(server,/metadata\.google\.internal/);assert.doesNotMatch(launcher,/sessionToken.*URLSearchParams|access_token|refresh_token/i);assert.match(launcher,/handoff_code/);assert.doesNotMatch(productionPortal,/handoff_code|storeOperationsHandoffIssueV1/);});

test("migration is private, atomic, PKCE-bound and browser-denied",()=>{const sql=readFileSync("supabase/migrations/20260823011845_store_operations_secure_session_handoff.sql","utf8");for(const pattern of [/force row level security/,/consumed_at is null/,/code_challenge/,/STORE_OPERATIONS_STAGING_SESSION_HANDOFF_V1/,/store_operations_staging_handoff_exchange_v1/,/\/auth\/callback/,/STORE_OPERATIONS_HANDOFF_SERVER_ONLY/,/store_operations_uat_resolve_hub_employee_access_v1/])assert.match(sql,pattern);assert.match(sql,/revoke all on function public\.store_operations_handoff_consume_v1[\s\S]*from public,anon,authenticated/);});
