import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

const root = new URL("../../", import.meta.url);
const backend = await readFile(new URL("supabase/functions/nov-hub-api/index.ts", root), "utf8");
const module = await readFile(new URL("supabase/functions/nov-hub-api/organization_health_monitoring_candidate.ts", root), "utf8");
const frontend = await readFile(new URL("portal/idea-link-app/index.html", root), "utf8");
const api = await readFile(new URL("portal/js/api.js", root), "utf8");
const migration = await readFile(new URL("supabase/idea-link-activity-followups-20260724.sql", root), "utf8");
let passed = 0;
const test = (fn) => { fn(); passed += 1; };
test(() => assert.match(module, /PUBLIC_RECEIVE_ACTIVITY_STOPPED/));
test(() => assert.match(module, /NO_PUBLIC_RECEIVE_ACTIVITY/));
test(() => assert.match(module, /FOLLOWUP_STATUSES/));
test(() => assert.match(module, /assertExactPayload\(payload\)/));
test(() => assert.match(backend, /ideaLinkActivityFollowupSave/));
test(() => assert.match(api, /"ideaLinkActivityFollowupSave"/));
test(() => assert.match(frontend, /saveActivityFollowup/));
test(() => assert.doesNotMatch(frontend, /離職予測スコア|モチベーションスコア|個人ランキング/));
test(() => assert.match(migration, /enable row level security/i));
test(() => assert.match(migration, /revoke all.+anon, authenticated/i));
test(() => assert.match(migration, /grant select, insert, update.+service_role/i));
test(() => assert.match(migration, /unique \(target_employee_id\)/i));
test(() => assert.doesNotMatch(migration, /\b(drop\s+table|alter\s+table[\s\S]*\brename\b|delete\s+from|truncate\s+table)\b/i));
test(() => assert.doesNotMatch(migration, /\b(textarea|note|comment|body)\b/i));
test(() => assert.match(migration, /^begin;/i));
test(() => assert.match(migration, /commit;\s*$/i));
test(() => assert.doesNotMatch(module, /notification|line.?works|enqueue/i));
test(() => assert.match(module, /visibility: "eq\.public"/));
console.log(JSON.stringify({ scenarios: 18, passed }));
